// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/cloudplayer/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as download$0 from "./internal/cloudplayer/download/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importplaylist$0 from "./internal/cloudplayer/importplaylist/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lyrics$0 from "./internal/cloudplayer/lyrics/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {number} playlistID
 * @param {importplaylist$0.ImportedTrackDTO[]} items
 * @returns {$CancellablePromise<void>}
 */
export function AppendPlaylistImportItems(playlistID, items) {
    return $Call.ByID(2280251046, playlistID, items);
}

/**
 * @param {string} songID
 * @returns {$CancellablePromise<string>}
 */
export function CachePreviewForPlay(songID) {
    return $Call.ByID(2779814344, songID);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<number>}
 */
export function CreatePlaylist(name) {
    return $Call.ByID(2432301559, name);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function DBStatus() {
    return $Call.ByID(2639592217);
}

/**
 * @param {number} playlistID
 * @returns {$CancellablePromise<void>}
 */
export function DeletePlaylist(playlistID) {
    return $Call.ByID(1874744072, playlistID);
}

/**
 * @param {number} playlistID
 * @param {number} itemID
 * @returns {$CancellablePromise<void>}
 */
export function DeletePlaylistImportItem(playlistID, itemID) {
    return $Call.ByID(2375995510, playlistID, itemID);
}

/**
 * @param {download$0.DownloadJob} job
 * @returns {$CancellablePromise<void>}
 */
export function EnqueueDownload(job) {
    return $Call.ByID(783403925, job);
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.SharePlaylistResponse>}
 */
export function FetchSharePlaylist(rawURL) {
    return $Call.ByID(1158076056, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {lyrics$0.FetchRequest} req
 * @returns {$CancellablePromise<string | null>}
 */
export function FetchSongLRCEnriched(req) {
    return $Call.ByID(3474565065, req);
}

/**
 * @param {string} songID
 * @returns {$CancellablePromise<string>}
 */
export function GetPreviewURL(songID) {
    return $Call.ByID(1951349590, songID);
}

/**
 * @returns {$CancellablePromise<config$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(107746166).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideMainWindow() {
    return $Call.ByID(3066344696);
}

/**
 * @returns {$CancellablePromise<$models.LocalSongRow[]>}
 */
export function ListLocalSongs() {
    return $Call.ByID(817478326).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {number} playlistID
 * @returns {$CancellablePromise<$models.PlaylistImportItemRow[]>}
 */
export function ListPlaylistImportItems(playlistID) {
    return $Call.ByID(3153693406, playlistID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PlaylistRow[]>}
 */
export function ListPlaylists() {
    return $Call.ByID(571711640).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RecentPlayRow[]>}
 */
export function ListRecentPlays() {
    return $Call.ByID(3719470761).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function LocalPathAccessible(path) {
    return $Call.ByID(1684743721, path);
}

/**
 * @param {string} text
 * @param {string} format
 * @returns {$CancellablePromise<importplaylist$0.ImportedTrackDTO[]>}
 */
export function ParseImportText(text, format) {
    return $Call.ByID(604755238, text, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(2326759433);
}

/**
 * @param {$models.RecentPlayIn} row
 * @returns {$CancellablePromise<void>}
 */
export function RecordRecentPlay(row) {
    return $Call.ByID(3648953193, row);
}

/**
 * @param {number} playlistID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenamePlaylist(playlistID, name) {
    return $Call.ByID(1505279409, playlistID, name);
}

/**
 * @param {number} playlistID
 * @param {importplaylist$0.ImportedTrackDTO[]} items
 * @returns {$CancellablePromise<void>}
 */
export function ReplacePlaylistImportItems(playlistID, items) {
    return $Call.ByID(4026698380, playlistID, items);
}

/**
 * @param {string} songID
 * @param {string} title
 * @param {string} artist
 * @returns {$CancellablePromise<$models.ResolveOnlinePlayOut>}
 */
export function ResolveOnlinePlay(songID, title, artist) {
    return $Call.ByID(3264812082, songID, title, artist).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {$models.SettingsPatch} patch
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(patch) {
    return $Call.ByID(2963223009, patch);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.ScanMusicFolderResult>}
 */
export function ScanMusicFolder(path) {
    return $Call.ByID(1885705547, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} keyword
 * @param {number} page
 * @returns {$CancellablePromise<$models.SearchResponse>}
 */
export function SearchSongs(keyword, page) {
    return $Call.ByID(1830530133, keyword, page).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {boolean} ignoreCursorEvents
 * @returns {$CancellablePromise<void>}
 */
export function SetDesktopLyricsClickThrough(ignoreCursorEvents) {
    return $Call.ByID(3757253524, ignoreCursorEvents);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowMainWindow() {
    return $Call.ByID(2970390533);
}

/**
 * @param {number} playlistID
 * @returns {$CancellablePromise<void>}
 */
export function StartImportEnrich(playlistID) {
    return $Call.ByID(16697315, playlistID);
}

// Private type creation functions
const $$createType0 = $models.SharePlaylistResponse.createFrom;
const $$createType1 = config$0.Settings.createFrom;
const $$createType2 = $models.LocalSongRow.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.PlaylistImportItemRow.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.PlaylistRow.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.RecentPlayRow.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = importplaylist$0.ImportedTrackDTO.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ResolveOnlinePlayOut.createFrom;
const $$createType13 = $models.ScanMusicFolderResult.createFrom;
const $$createType14 = $models.SearchResponse.createFrom;
