// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.WindowCreateRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function EnsureWindow(req) {
    return $Call.ByID(2236876807, req);
}

/**
 * @param {string} label
 * @returns {$CancellablePromise<$models.WindowInfo>}
 */
export function GetWindowInfo(label) {
    return $Call.ByID(635483299, label).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} label
 * @param {boolean} ignore
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowIgnoreMouseEvents(label, ignore) {
    return $Call.ByID(4277974361, label, ignore);
}

// Private type creation functions
const $$createType0 = $models.WindowInfo.createFrom;
