// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importplaylist$0 from "./internal/cloudplayer/importplaylist/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as musicsource$0 from "./internal/cloudplayer/musicsource/models.js";

export class HotkeyApplyReport {
    /**
     * Creates a new HotkeyApplyReport instance.
     * @param {Partial<HotkeyApplyReport>} [$$source = {}] - The source object to create the HotkeyApplyReport.
     */
    constructor($$source = {}) {
        if (!("play_pause" in $$source)) {
            /**
             * @member
             * @type {HotkeyEntryStatus}
             */
            this["play_pause"] = (new HotkeyEntryStatus());
        }
        if (!("prev" in $$source)) {
            /**
             * @member
             * @type {HotkeyEntryStatus}
             */
            this["prev"] = (new HotkeyEntryStatus());
        }
        if (!("next" in $$source)) {
            /**
             * @member
             * @type {HotkeyEntryStatus}
             */
            this["next"] = (new HotkeyEntryStatus());
        }
        if (!("volume_up" in $$source)) {
            /**
             * @member
             * @type {HotkeyEntryStatus}
             */
            this["volume_up"] = (new HotkeyEntryStatus());
        }
        if (!("volume_down" in $$source)) {
            /**
             * @member
             * @type {HotkeyEntryStatus}
             */
            this["volume_down"] = (new HotkeyEntryStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyApplyReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyApplyReport}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("play_pause" in $$parsedSource) {
            $$parsedSource["play_pause"] = $$createField0_0($$parsedSource["play_pause"]);
        }
        if ("prev" in $$parsedSource) {
            $$parsedSource["prev"] = $$createField1_0($$parsedSource["prev"]);
        }
        if ("next" in $$parsedSource) {
            $$parsedSource["next"] = $$createField2_0($$parsedSource["next"]);
        }
        if ("volume_up" in $$parsedSource) {
            $$parsedSource["volume_up"] = $$createField3_0($$parsedSource["volume_up"]);
        }
        if ("volume_down" in $$parsedSource) {
            $$parsedSource["volume_down"] = $$createField4_0($$parsedSource["volume_down"]);
        }
        return new HotkeyApplyReport(/** @type {Partial<HotkeyApplyReport>} */($$parsedSource));
    }
}

export class HotkeyEntryStatus {
    /**
     * Creates a new HotkeyEntryStatus instance.
     * @param {Partial<HotkeyEntryStatus>} [$$source = {}] - The source object to create the HotkeyEntryStatus.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyEntryStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyEntryStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyEntryStatus(/** @type {Partial<HotkeyEntryStatus>} */($$parsedSource));
    }
}

export class LocalSongRow {
    /**
     * Creates a new LocalSongRow instance.
     * @param {Partial<LocalSongRow>} [$$source = {}] - The source object to create the LocalSongRow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("file_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalSongRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalSongRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalSongRow(/** @type {Partial<LocalSongRow>} */($$parsedSource));
    }
}

export class PlaylistImportItemRow {
    /**
     * Creates a new PlaylistImportItemRow instance.
     * @param {Partial<PlaylistImportItemRow>} [$$source = {}] - The source object to create the PlaylistImportItemRow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album"] = "";
        }
        if (!("pjmp3_source_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pjmp3_source_id"] = "";
        }
        if (!("cover_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cover_url"] = "";
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistImportItemRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaylistImportItemRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistImportItemRow(/** @type {Partial<PlaylistImportItemRow>} */($$parsedSource));
    }
}

export class PlaylistRow {
    /**
     * Creates a new PlaylistRow instance.
     * @param {Partial<PlaylistRow>} [$$source = {}] - The source object to create the PlaylistRow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaylistRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistRow(/** @type {Partial<PlaylistRow>} */($$parsedSource));
    }
}

export class RecentPlayIn {
    /**
     * Creates a new RecentPlayIn instance.
     * @param {Partial<RecentPlayIn>} [$$source = {}] - The source object to create the RecentPlayIn.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("cover_url" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["cover_url"] = null;
        }
        if (!("pjmp3_source_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["pjmp3_source_id"] = null;
        }
        if (!("file_path" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["file_path"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentPlayIn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentPlayIn}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentPlayIn(/** @type {Partial<RecentPlayIn>} */($$parsedSource));
    }
}

export class RecentPlayRow {
    /**
     * Creates a new RecentPlayRow instance.
     * @param {Partial<RecentPlayRow>} [$$source = {}] - The source object to create the RecentPlayRow.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("cover_url" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["cover_url"] = null;
        }
        if (!("pjmp3_source_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["pjmp3_source_id"] = null;
        }
        if (!("file_path" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["file_path"] = null;
        }
        if (!("played_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["played_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentPlayRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentPlayRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentPlayRow(/** @type {Partial<RecentPlayRow>} */($$parsedSource));
    }
}

export class ResolveOnlinePlayOut {
    /**
     * Creates a new ResolveOnlinePlayOut instance.
     * @param {Partial<ResolveOnlinePlayOut>} [$$source = {}] - The source object to create the ResolveOnlinePlayOut.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (!("via" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["via"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveOnlinePlayOut instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolveOnlinePlayOut}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolveOnlinePlayOut(/** @type {Partial<ResolveOnlinePlayOut>} */($$parsedSource));
    }
}

export class ScanMusicFolderResult {
    /**
     * Creates a new ScanMusicFolderResult instance.
     * @param {Partial<ScanMusicFolderResult>} [$$source = {}] - The source object to create the ScanMusicFolderResult.
     */
    constructor($$source = {}) {
        if (!("audio_files_seen" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["audio_files_seen"] = 0;
        }
        if (!("rows_written" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows_written"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanMusicFolderResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanMusicFolderResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanMusicFolderResult(/** @type {Partial<ScanMusicFolderResult>} */($$parsedSource));
    }
}

export class SearchResponse {
    /**
     * Creates a new SearchResponse instance.
     * @param {Partial<SearchResponse>} [$$source = {}] - The source object to create the SearchResponse.
     */
    constructor($$source = {}) {
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {musicsource$0.SearchResult[]}
             */
            this["results"] = [];
        }
        if (!("has_next" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_next"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new SearchResponse(/** @type {Partial<SearchResponse>} */($$parsedSource));
    }
}

export class SettingsPatch {
    /**
     * Creates a new SettingsPatch instance.
     * @param {Partial<SettingsPatch>} [$$source = {}] - The source object to create the SettingsPatch.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["volume"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_library_folder"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["daily_download_limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["desktop_lyrics_visible"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["desktop_lyrics_locked"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_x"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_y"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_height"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_scale"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["download_folder"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["lyrics_netease_api_base"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["lyrics_lrclib_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["lyrics_provider_order"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["main_window_close_action"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["app_theme"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["app_theme_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["app_theme_custom_accent"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["desktop_lyrics_color_base"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["desktop_lyrics_color_highlight"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["share_netease_cookie_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["share_netease_cookie"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsPatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsPatch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsPatch(/** @type {Partial<SettingsPatch>} */($$parsedSource));
    }
}

export class SharePlaylistResponse {
    /**
     * Creates a new SharePlaylistResponse instance.
     * @param {Partial<SharePlaylistResponse>} [$$source = {}] - The source object to create the SharePlaylistResponse.
     */
    constructor($$source = {}) {
        if (!("playlist_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["playlist_name"] = "";
        }
        if (!("tracks" in $$source)) {
            /**
             * @member
             * @type {importplaylist$0.ImportedTrackDTO[]}
             */
            this["tracks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharePlaylistResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SharePlaylistResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tracks" in $$parsedSource) {
            $$parsedSource["tracks"] = $$createField1_0($$parsedSource["tracks"]);
        }
        return new SharePlaylistResponse(/** @type {Partial<SharePlaylistResponse>} */($$parsedSource));
    }
}

export class WindowCreateRequest {
    /**
     * Creates a new WindowCreateRequest instance.
     * @param {Partial<WindowCreateRequest>} [$$source = {}] - The source object to create the WindowCreateRequest.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("resizable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["resizable"] = false;
        }
        if (!("always_on_top" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["always_on_top"] = false;
        }
        if (!("decorations" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["decorations"] = false;
        }
        if (!("transparent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["transparent"] = false;
        }
        if (!("shadow" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["shadow"] = false;
        }
        if (!("skip_taskbar" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skip_taskbar"] = false;
        }
        if (!("focus" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["focus"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowCreateRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowCreateRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowCreateRequest(/** @type {Partial<WindowCreateRequest>} */($$parsedSource));
    }
}

export class WindowInfo {
    /**
     * Creates a new WindowInfo instance.
     * @param {Partial<WindowInfo>} [$$source = {}] - The source object to create the WindowInfo.
     */
    constructor($$source = {}) {
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowInfo(/** @type {Partial<WindowInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HotkeyEntryStatus.createFrom;
const $$createType1 = musicsource$0.SearchResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = importplaylist$0.ImportedTrackDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
