import { bootCloudPlayerApp } from "./bootstrap.js";

// Startup runtime translates composed modules into the final DOM/bootstrap wiring.
export function startDesktopRuntime(deps) {
  bootCloudPlayerApp({
    alertRequestFailed: deps.alertRequestFailed,
    applyAppTheme: deps.applyAppTheme,
    applyPlatformClassNames: deps.applyPlatformClassNames,
    applyLyricsPayload: deps.player.applyLyricsPayload,
    broadcastDesktopLyricsLock: deps.player.broadcastDesktopLyricsLock,
    broadcastTrayPlayerState: deps.player.broadcastTrayPlayerState,
    emitTo: deps.emitTo,
    ensureLrcLoadedForCurrentTrack: deps.player.ensureLrcLoadedForCurrentTrack,
    getCurrentPlayableKey: deps.player.currentPlayableKey,
    getPlayIndex: deps.getPlayIndex,
    getPlayLoadGeneration: deps.getPlayLoadGeneration,
    getPlayQueue: deps.getPlayQueue,
    getSelectedPlaylistId: deps.getSelectedPlaylistId,
    getSelectedPlaylistName: deps.getSelectedPlaylistName,
    getSettingsFormValues: deps.settings.getSettingsFormValues,
    invoke: deps.invoke,
    listen: deps.listen,
    loadPlaylistDetail: deps.loadPlaylistDetail,
    loadRecentPlaysFromDb: deps.player.loadRecentPlaysFromDb,
    loadSettings: deps.settings.loadSettings,
    lyricsReplaceTarget: deps.lyricsReplaceTarget,
    mainWindowCloseAction: deps.getMainWindowCloseAction,
    normalizeAppThemeMode: deps.normalizeAppThemeMode,
    onDownloadTaskChanged: deps.player.applyDownloadTaskChanged,
    onLyricsLockSync: deps.onLyricsLockSync,
    onSystemThemeChange: () => {},
    openLyricsReplaceWindow: deps.player.openLyricsReplaceWindow,
    openCloseConfirmModal: deps.settings.openCloseConfirmModal,
    player: deps.player,
    refreshLyricsLockMenuLabel: deps.player.refreshLyricsLockMenuLabel,
    renderDailyTable: deps.renderDailyTable,
    renderImportTable: deps.renderImportTable,
    renderMainShell: deps.renderMainShell,
    renderPlaylistSearchResults: deps.pages.renderPlaylistSearchResults,
    renderQueuePanel: deps.renderQueuePanel,
    renderSearchTable: deps.pages.renderSearchTable,
    renderSidebar: deps.pages.renderSidebar,
    searchState: deps.searchState,
    playAllDailyRecommendations: deps.pages.playAllDailyRecommendations,
    setPage: deps.setPage,
    setSearchScope: deps.pages.setSearchScope,
    syncDesktopLyricsState: deps.player.syncDesktopLyricsState,
    syncTrayCommand: deps.syncTrayCommand,
    systemDarkMedia: deps.systemDarkMedia,
    updateSearchToolbar: deps.pages.updateSearchToolbar,
    updateSearchViewState: deps.pages.updateSearchViewState,
    saveDailyRecommendationsAsPlaylist: deps.pages.saveDailyRecommendationsAsPlaylist,
    wireAccountCenter: deps.wireAccountCenter,
    wireAudio: deps.player.wireAudio,
    wireDiscoverToolbar: deps.pages.wireDiscoverToolbar,
    wireDockBar: deps.dock.wireDockBar,
    wireDownloadPage: deps.player.wireDownloadPage,
    wireGlobalHotkeyListener: deps.hotkeys.wireGlobalHotkeyListener,
    wireImportPage: deps.pages.wireImportPage,
    wirePlaylistPage: deps.pages.wirePlaylistPage,
    wirePreferencesModals: deps.settings.wirePreferencesModals,
    wireQueueToggle: deps.pages.wireQueueToggle,
    wireSearchPage: deps.pages.wireSearchPage,
    wireVolume: deps.hotkeys.wireVolume,
  });
}
