// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ImportedTrackDTO {
    /**
     * Creates a new ImportedTrackDTO instance.
     * @param {Partial<ImportedTrackDTO>} [$$source = {}] - The source object to create the ImportedTrackDTO.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportedTrackDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportedTrackDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportedTrackDTO(/** @type {Partial<ImportedTrackDTO>} */($$parsedSource));
    }
}
