// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GlobalHotkeys {
    /**
     * Creates a new GlobalHotkeys instance.
     * @param {Partial<GlobalHotkeys>} [$$source = {}] - The source object to create the GlobalHotkeys.
     */
    constructor($$source = {}) {
        if (!("play_pause" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["play_pause"] = "";
        }
        if (!("prev" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prev"] = "";
        }
        if (!("next" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["next"] = "";
        }
        if (!("volume_up" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["volume_up"] = "";
        }
        if (!("volume_down" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["volume_down"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalHotkeys instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlobalHotkeys}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlobalHotkeys(/** @type {Partial<GlobalHotkeys>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["window_geometry_b64"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["window_state_b64"] = undefined;
        }
        if (!("volume" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["volume"] = 0;
        }
        if (!("last_library_folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_library_folder"] = "";
        }
        if (!("daily_download_limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daily_download_limit"] = 0;
        }
        if (!("desktop_lyrics_visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["desktop_lyrics_visible"] = false;
        }
        if (!("desktop_lyrics_locked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["desktop_lyrics_locked"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_x"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_y"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["desktop_lyrics_height"] = undefined;
        }
        if (!("desktop_lyrics_scale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["desktop_lyrics_scale"] = 0;
        }
        if (!("download_folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_folder"] = "";
        }
        if (!("downloads_today_date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloads_today_date"] = "";
        }
        if (!("downloads_today_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloads_today_count"] = 0;
        }
        if (!("lyrics_netease_api_base" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lyrics_netease_api_base"] = "";
        }
        if (!("network_proxy_mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["network_proxy_mode"] = "";
        }
        if (!("network_proxy_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["network_proxy_url"] = "";
        }
        if (!("lyrics_lrclib_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lyrics_lrclib_enabled"] = false;
        }
        if (!("lyrics_provider_order" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lyrics_provider_order"] = "";
        }
        if (!("main_window_close_action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["main_window_close_action"] = "";
        }
        if (!("app_theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_theme"] = "";
        }
        if (!("app_theme_mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_theme_mode"] = "";
        }
        if (!("app_theme_custom_accent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_theme_custom_accent"] = "";
        }
        if (!("global_hotkeys" in $$source)) {
            /**
             * @member
             * @type {GlobalHotkeys}
             */
            this["global_hotkeys"] = (new GlobalHotkeys());
        }
        if (!("desktop_lyrics_color_base" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desktop_lyrics_color_base"] = "";
        }
        if (!("desktop_lyrics_color_highlight" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desktop_lyrics_color_highlight"] = "";
        }
        if (!("share_netease_cookie_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["share_netease_cookie_enabled"] = false;
        }
        if (!("share_netease_cookie" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["share_netease_cookie"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField24_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("global_hotkeys" in $$parsedSource) {
            $$parsedSource["global_hotkeys"] = $$createField24_0($$parsedSource["global_hotkeys"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GlobalHotkeys.createFrom;
